### ISSUE TITLE
3개 이상의 DIMM 인식 문제

### ISSUE THREAD

**Issue by devbug** [lich426/FanCtrl#13]
SMBus.dll에서 어떤 때엔 2개를 인식하고 어떤 때엔 3개, 어떤 때엔 4개를 인식합니다.
Windows 부팅 시 딜레이 주고 실행하도록 하면 4개 다 인식할 확률이 좀 더 높습니다만, 이것도 그때 그때 다릅니다.
그걸 떠나서 부팅 다 되고 나서 임의로 실행 시엔 4개 다 나와야 하는게 정상일거 같은데 결코 그렇게 안 됩니다.
웃긴게 1개만 인식되는 상황은 (경험상) 절대 발생하지 않습니다.

I2C 0x18~0x1B에서 2개가 나타나며 어느정도 랜덤하게 나타납니다.
이전에도 같은 문제가 있었으나 이전엔 무조건 2개는 나타나니까 이전 설정 파일 형식에선 DIMM 2개를 기준으로 잡기만 하면 뭐가 인식되든 상관없었는데, 이번엔 I2C 번호가 직접 삽입되므로 인식되지 않게 되면 팬 조절이 불가능해집니다.
심지어 그 상태에서 팬 조절 설정을 수정하면 이전 DIMM 조절 설정 중 인식되지 않은 DIMM 쪽 설정이 삭제됩니다.
즉, 최악의 경우 매번 새로 설정해야 하는 상황이 발생할 수 있습니다.

**Comment by lich426** [comment]
첨부한 SMBus.dll 로 교체한 다음 테스트 부탁 드립니다.
사용하시는 cpu도 알려주시면 좋구요ㅎㅎ
제가 인텔 10900k에 apex쓰느라 램도 두 개 밖에 없어서 3개 이상은 제대로 테스트를 못해봤네요
amd cpu에 램 3개 이상이면 더 좋을 듯 합니다

[SMBus.zip](https://github.com/lich426/FanCtrl/files/5843465/SMBus.zip)

**Comment by devbug** [comment]
수정된 SMBus.dll 확인했습니다.
제 시스템은 AMD Ryzen 7 5800X, G.SKILL Trident Z NEO 8 * 4 풀뱅, GIGABYTE X570 AORUS PRO, GIGABYTE 3080 AORUS MASTER입니다.
지연시간 0으로 주고 재부팅, 이후 종료해서 다시 실행 수 회 실시한 결과 정상 동작하는 것으로 보입니다. :)
