### ISSUE TITLE
UI Disappeared after starting minecraft(java edition)

### ISSUE THREAD

**Issue by EverettSummer** [lich426/FanCtrl#14]
<img width="664" alt="FanCtrl_AFXNwoIVW1" src="https://user-images.githubusercontent.com/55684557/105570653-be51d680-5d85-11eb-9fe3-06e39f22731c.png">
Not sure what causes this.

 I use this FanCtrl to enable automatic fan control because it's the only software that I found can control fans speed based on liquid temp. I have an NZXT Kraken X73 that works well with OpenHardwareMonitorLib (when I use the LibreHardwareMonitorLib, the liquid temp doesn't update)
My system is win10 19042
CPU: AMD Ryzen 5800x,
GPU is GTX1070

**Comment by EverettSummer** [comment]
Restart FanCtrl solves the issue

**Comment by lich426** [comment]
I can't test because I don't have minecraft game.
It is expected that there may have been a conflict in some game or anti virus program.
