### ISSUE TITLE
Closes (crashes?) after "Loading..." window.

### ISSUE THREAD

**Issue by RDru** [lich426/FanCtrl#15]
Installed 1.3.6. 
First time, no previous versions.
Have required .NET framework 4.6 and Visual redistributable 2019(x64), don't have Rivatuner. Windows 7.
Starting FanCtrl, "Loading.." window appears, then it closes after few seconds leaving no process.

**Comment by lich426** [comment]
I can't test it, because I don't have Windows 7 PC.
Does it have a crash in the lower version?

**Comment by lich426** [comment]
Close the issue because there is no response.
