### ISSUE TITLE
How to add new features?

### ISSUE THREAD

**Issue by xcasxcursex** [lich426/FanCtrl#18]
I've been using this app for a week or so now in place of Argus Monitor and it's working great :) Thanks!

I was thinking about a few changes I'd like to make, and I wasn't sure if you would want them, so I thought I should discuss with you whether you would prefer it if I were to submit patches to this project, or if you would object to my basing a new project on it instead?

Some of the things I have in mind are (in no order, some of these may be silly):

Dark mode
Plotting monitored data
Fan startup control (boosting fans briefly from 0% to a 100% so that they are sure to start spinning)
Disabling fan control entirely (enabling handover to BIOS control without exiting the app)
Ability to identify the cause of a fan's speed (which sensor is hot and making that fan spin?)
New RTSS overlay editor plugin support (ability to toggle between normal overlay and FanCtrl's by loading .ovl file)
Maybe fancy new UI, eg WinUI 3, etc (for a look like the https://github.com/Rem0o/FanControl.Releases/) (Not sure about this, performance-wise)
OpenRGB integration (RGB LED control)
Sensor interleaving (allow to read sensors not all at the same time, so load is spread out over time)
Separate sensor read timers for HDDs (SMART sensors tend to be slow and temps don't change quickly, so these can be read less often)

**Comment by lich426** [comment]
You can fork a project and use it.
Since the license for this project is GPL, all modified code must be disclosed.

**Comment by xcasxcursex** [comment]
OK thank you kindly :) I really enjoy it just how it is, so I'll take some time...

**Comment by xcasxcursex** [comment]
PS I hope they merge your DRAM patch upstream soon, it's great, thanks!
