### ISSUE TITLE
Sensors fail at start-up windows and memory leak

### ISSUE THREAD

**Issue by Damian-2001** [lich426/FanCtrl#19]
Hello! I am having a problem with FanCtrl. After waking the computer from sleep mode or start up FanCtrl with windows, the sensor values go bad and the fan control stops working.
I was able to find a way to fix it: if I open "CPUID HWMonitor", the sensor values are back, and I need to press the reload button to finally fix the problem (also tested with HWiNFO and Aida64 and not working)
What I also tried: All libraries disabled except LibreHardwareMonitor or the same but with OpenHardwareMonitor library; NvAPWrapper enabled/disabled

Also, I can verify with the task manager that the FanCtrl process is consuming a lot of RAM, but I am not sure if it is my system or some memory leak from the program.
Versions tested: 1.3.7, 1.3.8, 1.3.9
My system: Windows 7 Pro SP1 x64 7601. Asus B450M-A II. Latest AMD drivers installed.

Screenshots:
<a href="https://ibb.co/hysct63"><img src="https://i.ibb.co/hysct63/Fan-Ctrl-Issue2.jpg" alt="Fan-Ctrl-Issue2" border="0"></a>
<a href="https://ibb.co/QNPZbPN"><img src="https://i.ibb.co/QNPZbPN/fanctrl.png" alt="fanctrl" border="0"></a>

**Comment by lich426** [comment]
I can't check on Windows 7.
It should be used in Windows 10 at most likely.
and the wrong value is the OHM library issue.

**Comment by Damian-2001** [comment]
> It should be used in Windows 10 at most likely.
> and the wrong value is the OHM library issue.

Thanks for the reply
I can confirm that the memory problem is due to something in my system, since on another computer (also with windows 7) there is no leak
About the sensors, could you please elaborate on your answer, is there a solution? I'm not using the OpenHardwareMonitor library, only LibreHardwareMonitor
