### ISSUE TITLE
No Apply and Ok buttons.

### ISSUE THREAD

**Issue by romek71** [lich426/FanCtrl#2]
I have a small problem with the program. There are no Apply and Ok buttons in the Auto Fan Control window.
![screenshot 3](https://user-images.githubusercontent.com/67829150/86512759-28fcee00-be05-11ea-9bf1-f277784044a7.jpg)

**Comment by lich426** [comment]
Is OS Windows 7?
I haven't tested it on Windows 7.
And is it the same if I maximize the window?

**Comment by romek71** [comment]
This is OS Windows 7.
In the maximized window it is the same. In the OSD(RTSS) window the buttons are displayed correctly.

**Comment by lich426** [comment]
Can you try the this build?
[FanCtrl_v1.2.0a.zip](https://github.com/lich426/FanCtrl/raw/master/Portable/FanCtrl_v1.2.0a.zip)

**Comment by romek71** [comment]
This version works perfectly.
![screenshot 4](https://user-images.githubusercontent.com/67829150/86557407-51e0c880-bf56-11ea-85f0-449d67ceb817.jpg)

Thanks a lot for your help.
