### ISSUE TITLE
미지원 메인보드 문제

### ISSUE THREAD

**Issue by ss109natoa** [lich426/FanCtrl#20]
현재 Biostar B360GT3S 메인보드를 사용중입니다.
FanCtrl 프로그램 사용시 GPU 팬만 조절 가능하고,
CPU/케이스 팬은 확인이 불가능합니다.

LibreHardwareMonitorLib 혹은 OpenHardwareMonitorLib 에서 해당 메인보드를 지원하지 않으면
메인보드에 연결된 PWM 팬은 모니터링/컨트롤이 불가능하다고 보면 되나요?

**Comment by lich426** [comment]
맞습니다.
LHM 또는 OHM 라이브러리를 체크했는데 컨트롤 할 수 없다면 해당 메인보드는 지원하지 않는 것 입니다.
