### ISSUE TITLE
feature request: display both C and F at the same time

### ISSUE THREAD

**Issue by vanillaSprinkles** [lich426/FanCtrl#21]
Just gave this the quick run and test and would love to see both temps measurements displayed at once (as a toggle'able option)

**Comment by lich426** [comment]
Does it mean a tray icon context menu?

**Comment by vanillaSprinkles** [comment]
I was thinking an additional checkbox within the Options menu to to enable the feature, where all temps would have a C and F degrees (it would increase the max width of the main window).
