### ISSUE TITLE
Doesnt want to start.

### ISSUE THREAD

**Issue by DTG123** [lich426/FanCtrl#22]
had terrible day yesterday, was forced to reinstall win10.  Not sure what version I had installed previously.  This opens a loading  screen  says "loading...." for a few seconds and closes.

**Comment by lich426** [comment]
The program cannot read sensor information from your PC.
It's mostly a library problem. [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor)
