### ISSUE TITLE
Warning: Fans removed from configuration

### ISSUE THREAD

**Issue by xcasxcursex** [lich426/FanCtrl#24]
I'm very sorry I can't be more detailed, last night I updated to nvidia driver 496.49 and the day prior updated fanctrl to 1.43. Noticed today anything involving the GPU fan was just missing from fanctrl. Fan was sitting at minimum (30%) even under load despite no control being sent to it.

I expect this is a result of the driver upgrade and previous upgrades haven't done this, so be aware of that update.

**Comment by lich426** [comment]
I don't know what it means.

**Comment by xcasxcursex** [comment]
Good news is that I have a backup of the entire directory the day prior, the hardware.json and option.json are identical, the control,json has changed a lot but the entries have the same names... Honestly I can't see anything wrong. If my backups would be useful I am happy to share them?
