### ISSUE TITLE
why rtss not work properly

### ISSUE THREAD

**Issue by Blackstone1204** [lich426/FanCtrl#25]
after apply button click , cpu info seems  not show in  bottom left corner of screen,

what can i do next？

[
![image](https://user-images.githubusercontent.com/20477876/139778943-e0f1a644-2dd1-4a3a-9712-06f995d03f3c.png)
](url)

**Comment by Blackstone1204** [comment]
[
![image](https://user-images.githubusercontent.com/20477876/139779601-96f7785d-9a1d-4377-b5c5-7b9a04e68ba8.png)
](url)

**Comment by lich426** [comment]
The Rivatuner statistic server provides framerate and frametime monitoring support to the client applications. Framerate and frametime statistics is being collected for DirectX, OpenGL and VULKAN applications. The statistics can be rendered in On-Screen Display or provided to client applications connected to the server.
Read the description of rivatuner on this site. [https://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html](https://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html)
