### ISSUE TITLE
Lenovo Fan control support 

### ISSUE THREAD

**Issue by DragonFrizzy** [lich426/FanCtrl#30]
Dear lich426
I have Lenovo g585 and my chip is Ene KB9012QF A3 IC Chip and here is datasheet:https://drive.google.com/file/d/1FGc0qn5GGiFp37EKpOG3ocnW2LMmB_5s/view?usp=drivesdk
I would really appreciate if you could add support for my laptop I mean chip many thanks in advance for your attention ❤️
OS:Win11

**Comment by Luro223** [comment]
> Lenovo g585

Hello Dear DragonFrizzy as I know FanCtrl only supports PC not laptop
Use the specified app for your laptop like NotebookFanControl from hirschmann
Best regards
