### ISSUE TITLE
GPU fans override

### ISSUE THREAD

**Issue by Ghokury** [lich426/FanCtrl#32]
If any fans are linked to the GPU temps by automatic fan control, GPU fans curves are overwritten by the program. Probably, enabling any GPU monitoring libraries are enough for this.
I'd like to use 0db mode therefore I should keep the standard curve or use special option in MSI Afterburner.

**Comment by moya2162** [comment]
This is what i do to use 0db mode on my GPU. I fully use FanCtrl to control my GPU fan and i leave MSI Afterburner fan control off.

![image](https://user-images.githubusercontent.com/120048096/206320129-5fc61e9d-2ac9-43c4-83fa-d05f7e60a65d.png)

I'm also using NvAPIWrapper in the program settings.

**Comment by Ghokury** [comment]
> This is what i do to use 0db mode on my GPU. I fully use FanCtrl to control my GPU fan and i leave MSI Afterburner fan control off.
> 
> ![image](https://user-images.githubusercontent.com/120048096/206320129-5fc61e9d-2ac9-43c4-83fa-d05f7e60a65d.png)
> 
> I'm also using NvAPIWrapper in the program settings.

Do your fans stop after dropping below 60 C?
I already forgot about the issue and switched to Argus Monitor and started using a custom fan curve in Afterburner.

**Comment by Ghokury** [comment]
Try enabling 2 checkmarks in Afterburner. For me it turns fans off, but still works a bit weird. I couldn't make fans turn on 65 C instead of 60 and hysteresis doesn't work very well. Works in general tho.
![MSIAfterburner_rB0vkq4r3B](https://user-images.githubusercontent.com/73438721/206548535-388ed635-663d-4d1b-a1f5-fbdbefcea8ce.png)

**Comment by moya2162** [comment]
I wonder if FanCtrl could implement those 2 checkmarks. Ideally i would like to have 1 program control everything. 

![image](https://user-images.githubusercontent.com/120048096/206565376-87006301-f060-49a3-93cb-e71f25e752ad.png)

**Comment by lich426** [comment]
If you want to use Fanctrl and Afterburner at the same time, you don't have to control the gpu fan in Fanctrl

**Comment by moya2162** [comment]
I prefer fanctrl, I should have tested what Ghokury posted. Afterburner does not force 0 fan speed and functions exactly like fanctrl i.e. once displays are off the fans turn off as i previously described. Disregard my previous comment.
