### ISSUE TITLE
New delay option does not appear to be working correctly

### ISSUE THREAD

**Issue by moya2162** [lich426/FanCtrl#35]
Based on my testing the delay option added to the automatic fan control profiles would delay the change in fan speed by X amount of milliseconds. As long as the delay option is greater than the update rate of the sensors, it would be possible for example the CPU temperature to spike for 1 second then revert down to a lower temperature. The delay would then not change my fan speed for that quick temperature spike.  

![image](https://user-images.githubusercontent.com/120002161/206110488-1462ae11-4758-4e68-82ff-8d444998ae91.png)

If that is how it supposed to function, i have noticed that if i have a delay enabled, my fan speed gets locked at a higher temperature and does not recognize a temperature drop and reduce speed. When i set the delay to 0 ms, then the program updates the fan speed to my target percentage at its respective temperature. 

I am using version 1.5.5. It appears this issue occurs after i wake my computer up from sleep while FanCtrl is a background task.

**Comment by lich426** [comment]
Hasn't the fan been used in duplicate with the temperature sensor at another target?

**Comment by moya2162** [comment]
The fan curve shown in the picture is my CPU fan and that is not used in duplicate with the temperature sensor at another target.

**Comment by lich426** [comment]
I tested it. But I don't know what the problem is because it doesn't happen

**Comment by moya2162** [comment]
More data for you. This time i think the delay is causing an issue when the fan is mapped to two target temperatures sensors. 

My rear fan is mapped to both the CPU and GPU. I have done this because sometimes I'm doing CPU intensive tasks **_or_** GPU intensive tasks and want it to speed up during those operations. No delay everything works as expected. When i add the delay to the GPU temperature target, the fan was confused which temperature to follow and in my test it ended going with the CPU. I used a delay of 1 ms.

Here are my fan profiles.
[rear_fan_cpu_temp.txt](https://github.com/lich426/FanCtrl/files/10233359/rear_fan_cpu_temp.txt)
`{
  "step": false,
  "hysteresis": 2,
  "unit": 1,
  "auto": 0,
  "delay": 0,
  "value": [
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    45,
    60,
    60,
    60,
    60,
    60
  ]
}`

[rear_fan_gpu_temp.txt](https://github.com/lich426/FanCtrl/files/10233362/rear_fan_gpu_temp.txt)
`{
  "step": false,
  "hysteresis": 0,
  "unit": 1,
  "auto": 0,
  "delay": 1,
  "value": [
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    50,
    50,
    50,
    60,
    60,
    60,
    60,
    60,
    60,
    60
  ]
}`

Mapped to : `"id": "LHM/Control/lpc/nct6687d/control/*",` , where * is fan #

Let me know if you are unable to reproduce and i can do more testing on my end on a different computer.

**Comment by lich426** [comment]
If more than one temperature is registered, the fan operates at high PWM.
It has nothing to do with the delay option.

![1](https://user-images.githubusercontent.com/26077884/207776713-134a4e3a-5cf8-43b1-848d-856bb705b73c.png)
If the GPU temperature is 57C as shown in the figure, the PWM is 50%.

![2](https://user-images.githubusercontent.com/26077884/207776783-01fb128c-0c76-4370-bd27-1acef2c65228.png)
This is what CPU look like because the high PWM is 50%.

**Comment by moya2162** [comment]
Here is what mine looks like right now

Selected fan and targeted temperatures:
![1](https://user-images.githubusercontent.com/120048096/207797151-fa40f9c6-6634-42fa-ae05-a2dafef28d57.png)

Back fan on CPU target:
![2](https://user-images.githubusercontent.com/120048096/207797157-9374bebc-ddfe-4468-bb57-9c9388e29ea5.png)

Back fan on GPU target:
![3](https://user-images.githubusercontent.com/120048096/207797167-85b97d1a-94d6-4b8e-a626-8664789e7b4a.png)

Based on my settings, shouldn't my back fan be at 50% according to the pictures and not 58%? When i set delay to 0 ms it drops down to 50% as expected.

**Comment by lich426** [comment]
That's strange.
It works well on my PC.
I'll keep trying, but I don't recommend using the delay option.
