### ISSUE TITLE
3pin Chassis Fan stop working after enabling automatic fan control

### ISSUE THREAD

**Issue by jskgit** [lich426/FanCtrl#36]
In the picture below, Chassis Fan 2 is 3pin. So it does not appear in Fan control Section(Aux Fan is another one).
When I enable automatic fan control, Chassis Fan 2's RPM always goes down to 0.

![fanctrlreport](https://user-images.githubusercontent.com/6154922/207593165-adab2aac-03ad-4f74-b7b6-fa76ebae72ef.JPG)

**Comment by lich426** [comment]
Your motherboard doesn't seem to be properly supported by the [LHM library](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor)

**Comment by jskgit** [comment]
Ah yes. It is too old. But I did not think of it.
Thank you for your quick reply.
