### ISSUE TITLE
Won't recognize DIMM sensors

### ISSUE THREAD

**Issue by asacikay** [lich426/FanCtrl#37]
I have 2 Gskill F4-4000C16-16GVKA memory which has temperature sensors but doesn't get detected by FanCtrl. Hwinfo can show the dimm temperatures and on the tooltip it says the sensor is TSOD/TSE2002av/TSE2004av.

Motherboard: Asus X570 Crosshair VIII Hero Wifi
Windows 11

**Comment by lich426** [comment]
Check Hwinfo in the Options window and get DIMM temperature ([link](https://github.com/lich426/FanCtrl/releases/tag/v1.3.5))
