### ISSUE TITLE
Not an issue, but a thank you

### ISSUE THREAD

**Issue by bizzehdee** [lich426/FanCtrl#38]
I started creating this exact same project a couple of days ago, and somebody pointed me towards this project, and it turns out that you have already built exactly what it was i was aiming to build.

Thank you 😀

FYI, if you need any help adding features or fixing bugs, give me a ping and ill be happy to help.

**Comment by nemo-xs** [comment]
Yes. These functions are not just convenient, but absolutely necessary.
Riva is not always needed.
It would be great to see the current settings without having to open a full window.
