### ISSUE TITLE
Running the program from RUN

### ISSUE THREAD

**Issue by sick13** [lich426/FanCtrl#4]
So running the program from Start---Run creates the following files in *Username* folder
Options.json,OSD.json and Control.Json and not where the*.exe is
but if the program is run normaly with a double click then files are created in folder where the *.exe is

This is on Windows 7 X64 SP1

**Comment by lich426** [comment]
I couldn't test it because I didn't have a Windows 7 PC.
You mean the json file will be stored somewhere else?

**Comment by sick13** [comment]
this one works!
