### ISSUE TITLE
Power supply fan control?

### ISSUE THREAD

**Issue by Patricek0056** [lich426/FanCtrl#41]
Hello, I want to ask if it would be possible to implement the power supply fan control into FanCtrl.

**Comment by lich426** [comment]
I think it's probably impossible.
power fan is not connected to the motherboard and runs independently.

**Comment by Patricek0056** [comment]
Fine, maybe Windows API will support it in the future.

**Comment by Patricek0056** [comment]
Oh sorry, I didn't understood. Yes if you're saying that it runs independently, then it is impossible, I'm closing this issue as not planned.
