### ISSUE TITLE
Avast blocks the fanctrl.sys driver

### ISSUE THREAD

**Issue by Patricek0056** [lich426/FanCtrl#42]
### Problem description:
Avast Antivirus blocks the fanctrl.sys when the option “Block vulnerable kernel drivers” in Avast is enabled.

**Comment by Patricek0056** [comment]
![image](https://user-images.githubusercontent.com/69351811/221753249-c25bdfa9-0755-4c3d-bf6a-e97df876ddbb.png)

**Comment by lich426** [comment]
I've never used avast, so I don't know what the problem is.
If you can register the program as an exception, try it.

**Comment by Patricek0056** [comment]
Fine, but exception didn't helped. Can you at least test it on Virtual Machine or Windows Sandbox? (I'm using Avast Premium security).

**Comment by lich426** [comment]
The problem is that you should contact Avast. and VM probably does not support.
