### ISSUE TITLE
The FanCtrl taskbar tray icon uses non-standard menu design

### ISSUE THREAD

**Issue by Patricek0056** [lich426/FanCtrl#45]
### Problem description:
The FanCtrl menu under the FanCtrl tray icon uses non-standard menu design.

### Expected results:
The FanCtrl menu under the FanCtrl tray icon should use native menu design. 

### I will show an example in following screenshots:
FanCtrl uses the non-standard menu design in the system tray:
![FanCtrl's non-standard menu design](https://user-images.githubusercontent.com/69351811/222125333-4d2df231-bef3-448f-9f05-bd9e84d8d4e0.png)
The standard native menu design (in this case Avast Antivirus):
![Example of native menu design](https://user-images.githubusercontent.com/69351811/222125407-dc3719b1-d2a2-4a8f-8d72-242df8953fb7.png)

**Comment by lich426** [comment]
I'm not sure what you mean.
What is the definition of non-standard?

**Comment by Patricek0056** [comment]
It uses non-native/non-standard design.
