### ISSUE TITLE
FanCtrl Version 1.2.0 Program Bug in Task Manager on Windows 10

### ISSUE THREAD

**Issue by Reno-Sifana** [lich426/FanCtrl#5]
The known problem in the FanCtrl Version 1.2.0 program is that the FanCtrl Icon Always Appears in the Task Manager section of Apps when after entering the Windows 10 Desktop After Boot or Restart. It should be in the Background Apps section when Start up is minimized to the System Tray.
![2020-07-21](https://user-images.githubusercontent.com/68702583/88317553-a13f3b00-cd43-11ea-855c-289f0e74a33a.png)

**Comment by lich426** [comment]
I already know
but it's not a big problem, so I haven't fixed it yet

**Comment by lich426** [comment]
I solved this problem (v1.2.1)
