### ISSUE TITLE
fanclrl potentially dangerous? antivirus warning

### ISSUE THREAD

**Issue by Xant1k** [lich426/FanCtrl#50]
Today Microsoft Defender antivirus deleted the exe file, trying to download again is blocked.

Has anyone else encountered this?

**Comment by broizter** [comment]
Same thing happened to me today.

**Comment by lich426** [comment]
![1](https://user-images.githubusercontent.com/26077884/229988778-eadaad0a-b9aa-41c7-a81e-6191cd7ff042.png)
Register as an exception in Microsoft Defender.
Settings - Update & Security - Windows Security - Open Windows Security - Virus & threat protection tab - Manage settings - Add or remove exclusions - Add an exclusion - select folder - select a FanCtrl folder
