### ISSUE TITLE
Provide an installer, instead of only portable app exe.

### ISSUE THREAD

**Issue by DamianPereira** [lich426/FanCtrl#54]
Hi! I'd love to install this on my system as a full app instead of a portable .exe. Is this not supported or am I missing something?

**Comment by lich426** [comment]
Unable to support installation due to digital signature issues.

**Comment by DavidBrockmeier** [comment]
Please also keep the portable version. "Installers" that just copy files are a pet peeve of mine.

**Comment by lich426** [comment]
Sorry, I don't intend to support the installer
