### ISSUE TITLE
windows resize horizontally 

### ISSUE THREAD

**Issue by pnrxtx** [lich426/FanCtrl#55]
Minor ui recommendation to make window resizable horizontally also not only vertically.
Because of long motherboard names that don't fit in presized table cells, there appear scrolling bars on bottom.
This is with 100% dpi settings windows10.
And also window resizing is not saving after closing program.
![sa](https://github.com/lich426/FanCtrl/assets/88897538/c04143be-baf5-4064-91ff-fc7318053b72)

**Comment by lich426** [comment]
I'll apply it to the next update
