### ISSUE TITLE
Offering help to translate this project to spanish

### ISSUE THREAD

**Issue by robbie99us** [lich426/FanCtrl#56]
This software has helped me a lot. I could help translating to spanish as a contribution:)

**Comment by lich426** [comment]
[Language.xlsx](https://github.com/lich426/FanCtrl/files/12274397/Language.xlsx)
I would appreciate it if you could contribute to the translation

**Comment by robbie99us** [comment]
Sorry for being a little late, hope this helps
https://docs.google.com/spreadsheets/d/1v31cQ-t0BcEixbroQVpkbj8KhTcfEd27/edit?usp=sharing&ouid=117318219471503962823&rtpof=true&sd=true

**Comment by lich426** [comment]
Thank you, I'll apply it to the next update!

**Comment by Georgiy-Timoshin** [comment]
> Wow! Hi! Please add russian! https://docs.google.com/spreadsheets/d/1__5ju9IZMCYur3GAngYuZhHfgMuhusZz/edit?usp=sharing&ouid=108520832144585020075&rtpof=true&sd=true

Имеется несколько неточностей и опечаток, вот исправленный:
There are a few inaccuracies and typos, here is the corrected one:

[add russian Language.xlsx](https://github.com/lich426/FanCtrl/files/12444714/add.russian.Language.xlsx)

**Comment by dyatell** [comment]
> > Wow! Hi! Please add russian! https://docs.google.com/spreadsheets/d/1__5ju9IZMCYur3GAngYuZhHfgMuhusZz/edit?usp=sharing&ouid=108520832144585020075&rtpof=true&sd=true
> 
> Имеется несколько неточностей и опечаток, вот исправленный: There are a few inaccuracies and typos, here is the corrected one:
> 
> [add russian Language.xlsx](https://github.com/lich426/FanCtrl/files/12444714/add.russian.Language.xlsx)

Спасибо! Да уже ночью составлял таблицу, видать наделал ошибок)
Thanks! Yes, I was already making a table at night, I must have made mistakes)
