### ISSUE TITLE
it 8720f

### ISSUE THREAD

**Issue by Georgiy-Timoshin** [lich426/FanCtrl#58]
Good afternoon. Is it possible to add fan control support for the it 8720f multicontroller?
I use "SpeedFan", but it is already outdated.
P.S. Google translate)

**Comment by lich426** [comment]
I am not a backend developer. Any issue regarding hardware compatibility entirely depends on the following projects.
[https://github.com/LibreHardwareMonitor/LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor)

**Comment by Georgiy-Timoshin** [comment]
> I am not a backend developer. Any issue regarding hardware compatibility entirely depends on the following projects. https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

Reading data occurs, but cannot be controlled.
![изображение](https://github.com/lich426/FanCtrl/assets/38873082/ad4bc3c2-3651-4304-9d6a-7cec89f49272)
