### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by Georgiy-Timoshin** [lich426/FanCtrl#59]
The theme of the window for changing the color does not match the overall design.
![изображение](https://github.com/lich426/FanCtrl/assets/38873082/030382b1-248a-45de-9070-850557f403c4)

**Comment by lich426** [comment]
Fixed some issues that didn't apply to the theme https://github.com/lich426/FanCtrl/commit/e3e0c2f1b2d1b45650db4233cab6b165dfa277ca
