### ISSUE TITLE
Not detecting Gigabyte GPU at boot

### ISSUE THREAD

**Issue by tjader0** [lich426/FanCtrl#6]
When my computer boots I get an error from FanCtrl that hardware and Control.json do not match, and my GPU doesn't appear in the list:
![image](https://user-images.githubusercontent.com/81907/97378824-0efa8600-18a2-11eb-98ce-66a031c1e4e2.png)

After I close FanCtrl and open it again everything works as expected:
![image](https://user-images.githubusercontent.com/81907/97378855-26d20a00-18a2-11eb-8936-66d64ae1ae19.png)

I think FanCtrl might be starting before Gigabyte's service. I think the ideal solution would be to make FanCtrl a proper Windows Service, then it can declare a dependence on Gigabyte's service and be started after it.

An easier solution may be to just keep retrying until it can talk to the service.

**Comment by lich426** [comment]
Added delay time when running at windows startup
Check out v1.2.5
