### ISSUE TITLE
Scheduled values ​​do not apply.

### ISSUE THREAD

**Issue by Georgiy-Timoshin** [lich426/FanCtrl#65]
![изображение](https://github.com/lich426/FanCtrl/assets/38873082/6cdce10d-fa61-4188-a67c-27bed03b171e)

At startup, the values ​​according to the schedule are not applied.
![изображение](https://github.com/lich426/FanCtrl/assets/38873082/bafb676d-e4d4-4b17-b91d-f4419883e7c3)

After manually changing the value by at least one percent.
![изображение](https://github.com/lich426/FanCtrl/assets/38873082/9d9f4867-2805-4dec-bc04-3577d07047b6)

The state is being corrected, as shown in the graph.
![изображение](https://github.com/lich426/FanCtrl/assets/38873082/f326fdb1-b87b-47d6-9904-9a92a7cf21bc)

This problem is only on the motherboard, there is no such problem on the video card.
It's google translate!

**Comment by Georgiy-Timoshin** [comment]
My solution to the problem:
For "system fan 2": change the minimum value from 0% to 1%.

For "cpu fan": change the minimum value from 0% to 1%. And you also need to manually restart the program (click on the “restart” button).

![изображение](https://github.com/lich426/FanCtrl/assets/38873082/8ef7528a-e2ad-4326-af69-8703aa0799c8)
+ Connected the processor fan to the "system fan 2" connector. To avoid restarting the program manually.))

**Comment by lich426** [comment]
Depending on the motherboard, there might be a minimum PWM value, and in some cases, malfunctions can occur at 0%.
