### ISSUE TITLE
CPU fan speed cannot be controlled

### ISSUE THREAD

**Issue by T-machine57** [lich426/FanCtrl#67]
I am using FanCtrl on an ASUS motherboard (TUF GAMING H770-PRO WIFI), but I cannot control the CPU fan speed only.
It is recognized as Fan#3 on the motherboard and the RPM is displayed.
I changed the Fan control setting (Q-fan) of UEFI BIOS to DC mode or PWM mode, but it is fixed at 20~25% RPM regardless of CPU temperature fluctuation.

**Comment by T-machine57** [comment]
In addition, when the CPU fan control with FanCtrl is not set, it would be good if it could be controlled with the settings of the group UEFI BIOS, but at present, the CPU Fan speed is fixed at about 20~25% limit, which causes thermal throttling.

**Comment by lich426** [comment]
You should submit a pull request directly to the LMH library with the modifications you made.
