### ISSUE TITLE
Auto Fan Control window has wrong layout

### ISSUE THREAD

**Issue by tjader0** [lich426/FanCtrl#7]
For me in the Auto Fan Control window the buttons in the bottom are cut off and there is a big empty area in the right:

![image](https://user-images.githubusercontent.com/81907/97379091-baa3d600-18a2-11eb-808c-fe987f220b7f.png)

**Comment by lich426** [comment]
Maybe it's a window scaling problem.
I fixed the problem.(v1.2.5)

**Comment by tjader0** [comment]
The release has fixed it for me, thanks.
